export const navLinks = [
    {
        id: 'inicio',
        to: '/',
        label: 'Inicio',
        useScrollToTop: true,
        title: 'Ir al inicio',
        dataLink: 'navbar-inicio-link',
        dataLink2: 'footer-inicio-link',
    },
    {
        id: 'servicios',
        label: 'Servicios',
        useScrollToTop: true,
        title: 'Conoce los servicios de Flip Inmobiliaria',
        dataLink: 'navbar-servicios-link',
        dataLink2: 'footer-servicios-link',
        children: [
            { id: 'comprar', to: '/comprar', label: 'Comprar', title: 'Servicio de vompra Flip Inmobiliaria', dataCta: 'navbar-comprar-link' },
            { id: 'vender', to: '/vender', label: 'Vender', title: 'Servicio de venta Flip Inmobiliaria', dataCta: 'navbar-vender-link' },
            {
                id: 'remodelar',
                to: '/remodelar',
                label: 'Remodelar',
                title: 'Servicio de remodelado Flip Inmobiliaria',
                dataCta: 'navbar-remodelar-link',
            },
            { id: 'rentar', to: '/rentar', label: 'Rentar', title: 'Servicio de renta Flip Inmobiliaria', dataCta: 'navbar-rentar-link' },
            {
                id: 'infonavit',
                to: '/infonavit',
                label: 'Infonavit',
                title: 'Servicio de Infonavit Flip Inmobiliaria',
                dataCta: 'navbar-infonavit-link',
            },
        ],
    },
    {
        id: 'nosotros',
        to: '/nosotros',
        label: 'Nosotros',
        title: 'Conoce Flip Inmobiliaria',
        dataCta: 'navbar-nosotros-link',
        dataLink2: 'footer-nosotros-link',
    },
    {
        id: 'contacto',
        to: '/contacto',
        label: 'Contáctanos',
        title: 'Contactate con Flip Inmobiliaria',
        dataCta: 'navbar-contacto-link',
        dataCta2: 'footer-contacto-link',
    },
];
